```puml
@startuml
class function {
    std::vector<tiramisu::buffer *> function_arguments
    isl_union_map * dep_read_after_write
    isl_union_map * dep_write_after_write
    isl_union_map * dep_write_after_read
    isl_union_map * live_in_access
    isl_union_map * live_out_access
    isl_ast_node *ast
    std::vector<std::pair<std::string, int>> parallel_dimensions
    std::vector<std::tuple<std::string, int, int>> vector_dimensions
    std::vector<std::pair<std::string, int>> distributed_dimensions
    std::vector<std::pair<std::string, std::tuple<int, int, int>>> gpu_block_dimensions
    std::vector<std::pair<std::string, std::tuple<int, int, int>>> gpu_thread_dimensions
    std::vector<std::tuple<std::string, int, int>> unroll_dimensions
    std::vector<computation *> body
    - std::unordered_map<tiramisu::computation *, std::unordered_map<tiramisu::computation *, int>> sched_graph
    - std::unordered_map<tiramisu::computation *, std::unordered_map<tiramisu::computation *, int>> sched_graph_reversed
}

note left of function::function_arguments
  函数输入
end note
note left of function::dep_read_after_write
  相关依赖分析关系
end note
note left of function::parallel_dimensions
  这里parallel/vector/distributed
  gpu_block/gpu_thread/unroll
  都是为了记录迭代变量的tag
end note
note left of function::body
  按顺序记录所有的computation
end note
note left of function::sched_graph
  存储所有高层调度的邻接矩阵图, 从before指向after
end note
note left of function::sched_graph_reversed
  存储反向连接
end note
@enduml
```